name: mahfel_ons
description: "اپلیکیشن محفل انس - آثار دکتر محمد شیروی خوزانی"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.0
  url_launcher: ^6.2.0
  syncfusion_flutter_pdfviewer: any
  intl: ^0.20.3

flutter:
  uses-material-design: true
  assets:
   # - assets/mahfel_ons_animation.gif
   # - assets/logo.png
