name: shabha_daneshjooyi
description: "اپلیکیشن شب‌های دانشجویی - استاد شیروی"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # پکیج‌های شبکه و بارگذاری
  http: ^1.2.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  open_filex: ^4.5.0
  
  # نمایش پی‌دی‌اف
  syncfusion_flutter_pdfviewer: ^28.2.7
  
  # مدیریت اطلاعات دستگاه و زمان
  device_info_plus: ^11.2.0
  intl: any

  # نوتیفیکیشن روزانه ساعت ۱۷
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  # آیکون‌ها و ابزارها
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo-sh.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo-sh.png
